weni-ai/bothub-engine

bothub/api/serializers/__init__.py, bothub/api/serializers/repository.py, bothub/api/views.py
=> Update repository route use EditRepositorySerializer as serializer in write methods

bothub/api/serializers/example.py, bothub/api/tests/example.py, bothub/api/validators.py
=> Closes #99

bothub/api/validators.py, bothub/common/models.py
=> Resolve #102

bothub/api/serializers/repository.py, bothub/common/models.py, bothub/common/tests.py
=> Add repository update warnings

bothub/api/v1/serializers/category.py, bothub/api/v1/serializers/repository.py, bothub/api/v1/tests/test_categories.py
Add to RepositoryCategorySerializer new Repository category schema.
=> Add category icons to my repositories

README.md, bothub/api/v2/account/views.py, bothub/api/v2/tests/test_account.py, bothub/authentication/models.py, bothub/settings.py
if there is a repository whose user owns, the system replaces for the user of the system
=> Added route delete user

bothub/utils.py
added "v2" on url build in nlp_requests, with that, the method nlp_requests on utils will build the url in accoding with project's environment variables.
=> fix for url build in bothub/utils/nlp_requests

bothub/api/v2/nlp/views.py, bothub/api/v2/tests/test_nlp.py, bothub/common/models.py
Adjusting the filters by intention to be able to filter by repository version. Run black
=> add filter by repository version to intents nlp endpoint

bothub/common/models.py
reported bug:
[nlp response]
{'detail': 'There was an error parsing the body'}
=> convert body to json in request_nlp_analyze

bothub/api/v2/internal/connect_rest_client.py
Reverts Ilhasoft/bothub-engine#731
=> Revert "Feature/remove rest client from celery"

bothub/api/v2/repository/serializers.py, bothub/api/v2/repository/views.py, bothub/api/v2/routers.py, bothub/api/v2/tests/test_repository.py, bothub/api/v2/tests/test_tasks.py, bothub/api/v2/versionning/serializers.py, bothub/common/models.py, bothub/common/tasks.py, bothub/settings.py, docker-compose.yml
- Implement clone_repository celery task;
- Implement `clone-repository` endpoint;
- Implement testing for clone-repository API restrictions;
- Implement testing for clone_repository function (syncronously / without celery);
- Update clone_version celery task signature and the only reference to it in the code;
- Add "container_name"s on docker-compose for easier referencing;
- Fix ADMINS variable at bothub/settings.py which contained a personal email;
- Improve repository/info endpoint with explicit table joins, reducing a few queries from the API;
- Add serializer_class to RepositoryTokenByUserViewSet, which was raising an ocasional error at the API;
=> Merge to develop

bothub/authentication/models.py, bothub/settings.py
after disabling bothub api this url broke so now we set to connect webapp url to reset password
=> change api reset password, set connect url

bothub/api/v2/account/views.py, bothub/authentication/keycloak_rest_client.py
now get the user from keycloak first
=> adding keycloak rest client and changing view to create a token

CHANGELOG.md
adding changelog to application
=> update from 5.6.1 to 5.6.2

bothub/api/v2/repository/filters.py, bothub/api/v2/repository/views.py
Feature: Implement categories filter by Repository and add repository_type filter
=> Feature: Add more filters for Repository API

bothub/api/v2/zeroshot/usecases/format_classification.py, bothub/api/v2/zeroshot/usecases/format_prompt.py, bothub/api/v2/zeroshot/views.py
improving none class prompt, get language by prefix language and post processing classification
=> improving text post processing

bothub/api/v2/zeroshot/usecases/format_prompt.py, bothub/api/v2/zeroshot/views.py
Update prompt formatting by standardizing the way how we receive languages from flows
=> Update language codes

bothub/api/v2/repository/views.py, bothub/common/usecase/repositorylog/export.py
Fix wrong method syntax and entities typing.
=> Fix: Export logs

bothub/common/usecase/repositorylog/dto.py, bothub/common/usecase/repositorylog/export.py, bothub/common/usecase/repositorylog/storage.py
Temp s3 storage xlsx file, will be changed to assync  celery tasks next week.
=> Add: Temp storage for logs

bothub/api/v2/zeroshot/usecases/format_classification.py, bothub/api/v2/zeroshot/usecases/format_prompt.py, bothub/api/v2/zeroshot/views.py
This PR contains an update in the Zeroshot Prompt Formatting and Classification validation for the new model.
=> Update prompt and classification format for ZeroShot 3.3.14 model
